on: [ push, pull_request ]
name: Security
jobs:
    Gosec:
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v2
            -   name: Install Go
                uses: actions/setup-go@v2
                with:
                    go-version: '^1.17.6'
            -   name: Install Gosec
                run: |
                    export GO111MODULE=on
                    export PATH=${PATH}:`go env GOPATH`/bin
                    go install github.com/securego/gosec/v2/cmd/gosec@latest
                # -----
            -   name: Run Gosec (sentry)
                working-directory: ./sentry
                run: "`go env GOPATH`/bin/gosec -exclude-dir=internal ./..."
                # -----
            -   name: Run Gosec (paseto)
                working-directory: ./paseto
                run: "`go env GOPATH`/bin/gosec -exclude-dir=internal ./..."
                # -----
            -   name: Run Gosec (fiberzap)
                working-directory: ./fiberzap
                run: "`go env GOPATH`/bin/gosec -exclude-dir=internal ./..."
                # -----
            -   name: Run Gosec (otelfiber)
                working-directory: ./otelfiber
                run: "`go env GOPATH`/bin/gosec -exclude-dir=example ./..."
            -   name: Run Gosec (swagger)
                working-directory: ./swagger
                run: "`go env GOPATH`/bin/gosec -exclude-dir=internal ./..."
                # -----
            -   name: Run Gosec (casbin)
                working-directory: ./casbin
                run: "`go env GOPATH`/bin/gosec -exclude-dir=internal ./..."
                # -----
